# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Willow's Blog
email: didalgus@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://didalgus.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
#markdown: kramdown
#theme: minima
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-toc

markdown: kramdown

# Site Settings
locale  : "ko-KR" # 사이트의 언어 설정을 할 수있습니다.
timezone: Asia/Seoul

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


#blog logo
logo: "/assets/images/willow_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/index_title.jpg"

name: 'Weeping Willow'
author: 'Weeping Willow'
author_image: "/assets/images/author.jpg"

paginate:	5
permalink: /:year/:month/:day/:title.html

#used to display twitter cards
twitter_handle: '@willow1005'

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/willow1005
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/didalgus
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:


#Analytics
google_analytics: UA-142402158-1

#Comments
facebook_comments: 1
